"use strict";

// Update UI. The engine (toolkit UpdateService) finds/downloads/stages the update; we only draw the view.
//  - Auto ON (app.update.auto): the engine downloads + stages in the background -> "update-downloaded/-staged" -> bar: "restart".
//  - Auto OFF: the engine says "update-available / show-prompt" -> bar: "Download and install" (AppUpdater.allowUpdateDownload).
//  - "Check for updates" in the "Customize" panel -> manual check via AppUpdater; the status text is published as an event.
//  - On the first launch after an update, the RELEASE NOTES page on the site opens automatically (once; not on first install).
// Engine config: mozconfig (--enable-updater, channel "vento"), patches/0003 (MAR signing certs), 0004 (URL).

const { AppUpdater } = ChromeUtils.importESModule("resource://gre/modules/AppUpdater.sys.mjs");

Vento.update = new (class VentoUpdate extends EventTarget {
  // Single URL; pages generated by the site build (site/build.mjs) on the server. If the path changes, change ONLY this.
  static RELEASE_NOTES = {
    tr: "https://vento.cansoykanyilmaz.com/surum-notlari/",
    en: "https://vento.cansoykanyilmaz.com/en/release-notes/",
  };
  static PREF_LAST = "vento.lastRunVersion";

  #updater = null;
  #els = {};
  status = { id: "idle", text: "" };

  /** Release notes URL (by language) + ?v=<version>. */
  releaseNotesURL(version = Services.appinfo.version) {
    const base = VentoUpdate.RELEASE_NOTES[Vento.l10n.locale.startsWith("tr") ? "tr" : "en"];
    return `${base}?v=${encodeURIComponent(version)}`;
  }

  /**
   * First launch after an update? If the last run version is recorded and is LOWER than the current one, opens the release notes in a new tab.
   * Doesn't open on first install (no record) or on the same version. Returns the URL if it opened, null if not. ALWAYS updates the record.
   */
  afterUpdate({ last = Services.prefs.getStringPref(VentoUpdate.PREF_LAST, ""), current = Services.appinfo.version, open = true } = {}) {
    Services.prefs.setStringPref(VentoUpdate.PREF_LAST, current);
    if (!last || Services.vc.compare(last, current) >= 0) {
      return null;
    }
    const url = this.releaseNotesURL(current);
    if (open) {
      Vento.tabs.open(url, { select: true });
    }
    return url;
  }

  #set(id, key, args) {
    this.status = { id, text: key ? Vento.l10n.t(key, args) : "" };
    this.dispatchEvent(new CustomEvent("status", { detail: this.status }));
  }

  #showBar(kind) {
    const { bar, text, primary, later } = this.#els;
    text.textContent = Vento.l10n.t(kind === "ready" ? "ub-ready" : "ub-available");
    primary.textContent = Vento.l10n.t(kind === "ready" ? "ub-restart" : "ub-download");
    primary.dataset.kind = kind;
    Vento.motion.show(bar, "pop");
    return bar;
  }

  restart() {
    Services.startup.quit(Ci.nsIAppStartup.eAttemptQuit | Ci.nsIAppStartup.eRestart);
  }

  #onStatus(status, a, b) {
    const S = AppUpdater.STATUS;
    switch (status) {
      case S.CHECKING:
        this.#set("checking", "up-checking");
        break;
      case S.NO_UPDATES_FOUND:
        this.#set("current", "up-current", { version: Services.appinfo.version });
        break;
      case S.DOWNLOAD_AND_INSTALL:
        this.#set("found", "up-found");
        this.#showBar("available");
        break;
      case S.DOWNLOADING:
      case S.STAGING: {
        const percent = status === S.STAGING ? 100 : b ? Math.round((a / b) * 100) : 0;
        this.#set("downloading", "up-downloading", { percent });
        break;
      }
      case S.READY_FOR_RESTART:
        this.#set("ready", "up-ready");
        this.#showBar("ready");
        break;
      case S.NO_UPDATER:
      case S.UPDATE_DISABLED_BY_POLICY:
      case S.UNSUPPORTED_SYSTEM:
      case S.MANUAL_UPDATE:
        this.#set("unavailable", "up-unavailable");
        break;
      case S.DOWNLOAD_FAILED:
      case S.CHECKING_FAILED:
      case S.INTERNAL_ERROR:
        this.#set("failed", "up-failed");
        break;
    }
  }

  /** Manual/background check: AppUpdater states are reflected in the UI. `updater` is for tests (fake). */
  check(updater = new AppUpdater()) {
    this.#updater?.stop?.();
    this.#updater = updater;
    updater.addListener((status, a, b) => this.#onStatus(status, a, b));
    return updater.check();
  }

  init() {
    const $ = id => document.getElementById(id);
    this.#els = { bar: $("update-bar"), text: $("ub-text"), primary: $("ub-primary"), later: $("ub-later") };
    this.#els.later.addEventListener("click", () => Vento.motion.hide(this.#els.bar, "pop"));
    this.#els.primary.addEventListener("click", () => {
      if (this.#els.primary.dataset.kind === "ready") {
        this.restart();
      } else {
        this.#updater?.allowUpdateDownload?.();
        Vento.motion.hide(this.#els.bar, "pop");
      }
    });
    // The bar text refreshes when the language changes
    Vento.l10n.addEventListener("change", () => {
      if (!this.#els.bar.hidden) {
        this.#showBar(this.#els.primary.dataset.kind);
      }
    });
    const observer = {
      observe: (subject, topic, data) => {
        if (topic === "update-available" && data !== "show-prompt") {
          return; // only the "ask permission" state matters to us (auto off)
        }
        this.check(); // the state machine keeps going; the bar opens on READY_FOR_RESTART / DOWNLOAD_AND_INSTALL
      },
    };
    for (const topic of ["update-available", "update-downloaded", "update-staged"]) {
      Services.obs.addObserver(observer, topic);
    }
    window.addEventListener("unload", () => {
      for (const topic of ["update-available", "update-downloaded", "update-staged"]) {
        Services.obs.removeObserver(observer, topic);
      }
    }, { once: true });
  }
})();
