Classes = [
    {
        "cid": "{80b2bd50-970d-4d74-8ae1-5b39020fd685}",
        "contract_ids": ["@vento.app/startup;1"],
        "esModule": "resource:///modules/VentoStartup.sys.mjs",
        "constructor": "VentoStartup",
        "categories": {"command-line-handler": "m-vento"},
    },
]
